DROP TABLE IF EXISTS USERS;

CREATE TABLE USERS (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(250) NOT NULL,
  username VARCHAR(250) UNIQUE NOT NULL,
  email VARCHAR(250) NOT NULL,
  password VARCHAR(250) NOT NULL,
  role VARCHAR(250) NOT NULL
);

CREATE TABLE IMAGE (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(250) NOT NULL,
  link VARCHAR(250) UNIQUE NOT NULL,
  image_hash VARCHAR(250) UNIQUE NOT NULL,
  image_delete_hash VARCHAR(250) UNIQUE NOT NULL,
  user_name VARCHAR(250) FOREIGN KEY REFERENCES USERS
);